#ifndef _CONFIGOPTION_H_
#define _CONFIGOPTION_H_

// option for CDXCFG_FILE_SYSTEM.
#define OPTION_FILE_SYSTEM_LINUX_VFS    (0)
#define OPTION_FILE_SYSTEM_DIRECT_FATFS (1)
#define OPTION_FILE_SYSTEM_DIRECT_IO    (2)


#endif  /* _CONFIGOPTION_H_ */

