#ifndef CDX_CONFIG_H
#define CDX_CONFIG_H

#define CDX_MEDIA_TYPE_DISABLE_RMVB  (1<<0)
#define CDX_MEDIA_TYPE_DISABLE_AVI   (1<<1)
#define CDX_MEDIA_TYPE_DISABLE_FLV   (1<<2)
#define CDX_MEDIA_TYPE_DISABLE_PMP   (1<<3)
#define CDX_MEDIA_TYPE_DISABLE_ASF   (1<<4)
#define CDX_MEDIA_TYPE_DISABLE_MKV   (1<<5)
#define CDX_MEDIA_TYPE_DISABLE_MOV   (1<<6)
#define CDX_MEDIA_TYPE_DISABLE_MPG   (1<<7)
#define CDX_MEDIA_TYPE_DISABLE_TS    (1<<8)

#define CDX_CODEC_TYPE_DISABLE_MPEG2     (1<<16)
#define CDX_CODEC_TYPE_DISABLE_MPEG4     (1<<17)
#define CDX_CODEC_TYPE_DISABLE_REALVIDEO (1<<18)
#define CDX_CODEC_TYPE_DISABLE_H264      (1<<19)
#define CDX_CODEC_TYPE_DISABLE_VC1       (1<<20)
#define CDX_CODEC_TYPE_DISABLE_AVS       (1<<21)
#define CDX_CODEC_TYPE_DISABLE_MJPEG     (1<<22)
#define CDX_CODEC_TYPE_DISABLE_VP8       (1<<23)

#define CDX_CODEC_TYPE_DISABLE_AC3       (1<<24)
#define CDX_CODEC_TYPE_DISABLE_DTS       (1<<25)
#define CDX_CODEC_TYPE_DISABLE_WMA       (1<<26)
#define CDX_CODEC_TYPE_DISABLE_AAC       (1<<27)

#define CDX_VIDEO_CodingMPEG4_DIVX		 (1<<30)

#endif
